# Generated by Django 3.1.3 on 2021-03-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='timediff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.IntegerField(max_length=10)),
                ('end_time', models.IntegerField(max_length=10)),
            ],
        ),
    ]
