# Generated by Django 3.1.3 on 2021-03-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210315_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timediff',
            name='start_time',
            field=models.IntegerField(null=True),
        ),
    ]
