# Generated by Django 3.1.3 on 2021-03-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210315_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='timediff',
            name='time_difference',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timediff',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
