# Generated by Django 3.1.3 on 2021-03-17 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210316_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timediff',
            name='time_difference',
        ),
    ]
