# Generated by Django 3.1.3 on 2021-03-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_timediff_time_difference'),
    ]

    operations = [
        migrations.AddField(
            model_name='timediff',
            name='seconds',
            field=models.FloatField(null=True),
        ),
    ]
