# Generated by Django 3.1.3 on 2021-03-17 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_timediff_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timediff',
            name='seconds',
        ),
    ]
